### PR TITLE
Skeuomorph integration & Proto Source Generation Support

### LINKED ISSUE #379: Code Generation from Proto definitions
I'm trying to create `Scala` files from `proto` definitions but I'm getting this error:

`Unknown IDL type 'proto'. Valid values: avro`

My settings:

```
idlType := "proto",
srcGenSerializationType := "Protobuf",
srcGenTargetDir := (Compile / sourceManaged).value / "compiled_proto",
sourceGenerators in Compile += (srcGen in Compile).taskValue,
```

### PR DESCRIPTION
**Pull request by rafaparadela**
Closes #379 

Basically, lets the `idlgen` plugin generate Scala code from ProtocolBuffer protocols using Skeuomorph.

### CODE REVIEW

**Comment by rafaparadela** [comment]
Ready for review

File: modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/project/build.properties [hunk 1]
```diff
@@ -0,0 +1 @@
+sbt.version=1.1.5
```
Comment (juanpedromoreno) [inline modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/project/build.properties]: I think we can remove the build.properties file from scripted tests

File: modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+          .generateFrom(inputFile = protoFile, serializationType = "", options = "")
+          .map(t => (t._1, t._2.map(_.clean)))
+
+      result shouldBe Some(("com/proto/book.scala", Seq(expectation.clean)))
+    }
+  }
+
+  val expectation =
+    """package com.proto
+      |
```
Comment (juanpedromoreno) [inline modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala]: Out of curiosity, this code won't compile because we are not importing `fs2.Stream`, right?

File: modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/project/build.properties (hunk 1 above)
Comment (rafaparadela) [reply modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/project/build.properties]: 👍 Just cloned the most similar project. I'll do it.

File: modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala (hunk 2 above)
Comment (rafaparadela) [reply modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala]: Yes, exactly, it doesn't compile because of: `Stream`, `@message` and `@service`.
This is why I replaced the `> publishLocal` by `> srcGen` in the scripted test, since I just wanted to prove that the Scala code has been generated.

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+    println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
+    println(result.withImports.withCoproducts)
+
+    getPath(protobufProtocol) -> Seq(result.withImports.withCoproducts)
+  }
+
+  private def getPath(p: Protocol[Mu[ProtobufF]]): String =
+    s"${p.pkg.toPath}/${p.name}$ScalaFileExtension"
+
+  implicit class StringOps(self: String) {
```
Comment (fedefernandez) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: I'm not a huge fan of `implicit class` for adding extra defs. I prefer functions:
```scala
      val cleanCop: String => String =
        _.replace("Cop[", "").replace("::", ":+:").replace("TNil]", "CNil")

      val withImports: String => String = s =>
        (s.split("\n", 2).toList match {
          case h :: t =>
            List(
              h,
              "\n",
              "import higherkindness.mu.rpc.protocol._",
              "import fs2.Stream",
              "import shapeless.{:+:, CNil}") ++ t
          case a => a
        }).mkString("\n")

      val withCoproducts: String => String = s =>
        """((Cop\[)(((\w+)(\s)?(\:\:)(\s)?)+)(TNil)(\]))""".r.replaceAllIn(s, replacer => cleanCop(replacer.matched))

      val toPath: String => String = _.replace('.', '/')

// ...

      (withImports andThen withCoproducts)(result)
```

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+            h,
+            "\n",
+            "import higherkindness.mu.rpc.protocol._",
+            "import fs2.Stream",
+            "import shapeless.{:+:, CNil}") ++ t
+        case a => a
+      }).mkString("\n")
+
+    def withCoproducts: String =
+      """((Cop\[)(((\w+)(\s)?(\:\:)(\s)?)+)(TNil)(\]))""".r.replaceAllIn(self, _.matched.cleanCop)
```
Comment (fedefernandez) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Please, move the regex to a val, in order to avoid the initialization on each cal

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+
+    val printProtocol: higherkindness.skeuomorph.mu.Protocol[Mu[MuF]] => String = {
+      p: higherkindness.skeuomorph.mu.Protocol[Mu[MuF]] =>
+        higherkindness.skeuomorph.mu.print.proto.print(p)
+    }
+
+    val result: String = (parseProtocol andThen printProtocol)(protobufProtocol)
+
+    println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
+    println(result.withImports.withCoproducts)
```
[the remark this answers is not in the document]
Comment (rafaparadela) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Sorry I was debugging this sorry. Removed.

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+object ProtoSrcGenerator extends SrcGenerator {
+
+  private[this] val logger = getLogger
+
+  val idlType: String = proto.IdlType
+
+  def inputFiles(files: Set[File]): Seq[File] = {
+    val protoFiles = files.filter(_.getName.endsWith(ProtoExtension))
+    protoFiles.toSeq
+  }
```
[the remark this answers is not in the document]
Comment (rafaparadela) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Done at https://github.com/higherkindness/mu/pull/577/commits/58a34329032b5af9a42834fccaa414a9be1efde5

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+      inputFile: File,
+      serializationType: String,
+      options: String*): Option[(String, Seq[String])] = Option(getCode(inputFile))
+
+  private def getCode(file: File): (String, Seq[String]) = {
+
+    val source = ProtoSource(file.getName, file.getParent)
+
+    val protobufProtocol: Protocol[Mu[ProtobufF]] =
+      parseProto[IO, Mu[ProtobufF]].parse(source).unsafeRunSync()
```
[the remark this answers is not in the document]
Comment (rafaparadela) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Done at https://github.com/higherkindness/mu/pull/577/commits/58a34329032b5af9a42834fccaa414a9be1efde5

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala (hunk 3 above)
Comment (rafaparadela) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Done at https://github.com/higherkindness/mu/pull/577/commits/58a34329032b5af9a42834fccaa414a9be1efde5

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala (hunk 4 above)
Comment (rafaparadela) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Done at https://github.com/higherkindness/mu/pull/577/commits/58a34329032b5af9a42834fccaa414a9be1efde5

File: modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala (hunk 2 above)
Comment (rafaparadela) [reply modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala]: @juanpedromoreno After:
- Injecting some imports for dealing with `@message`, `@service`, `fs2.Stream`, `:+:` and `CNil`
- Adding some transformations to replace `Cop[A :: B :: TNil]` into `A :+: B :+: CNil`
- Adding the proper dependencies in the scripted test

The right compilation of the generates Scala code is being proved by `scripted sbt-mu-idlgen/srcProtoGenFromDirs`

Done at:
- https://github.com/higherkindness/mu/pull/577/commits/58a34329032b5af9a42834fccaa414a9be1efde5
- https://github.com/higherkindness/mu/pull/577/commits/1281ceef9eab991532923b9d91fc054082594ad9

File: modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/test [hunk 8]
```diff
@@ -0,0 +1,3 @@
+> compile
```
Comment (juanpedromoreno) [inline modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/test]: I changed it by `compile` since it's being generated in that `srcGen` is compiled in that stage

File: modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt [hunk 9]
```diff
@@ -0,0 +1,19 @@
+lazy val root = project
```
[the remark this answers is not in the document]
Comment (juanpedromoreno) [reply modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt]: @L-Lavigne Could we just add `aggregate`?

```scala
lazy val `idlgen-sbt` = project
  .in(file("modules/idlgen/plugin"))
  .dependsOn(`idlgen-core`)
  .aggregate(`idlgen-core`)
```

[the remark this answers is not in the document]
Comment (juanpedromoreno) [reply modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt]: I've just checked, we might need to add `aggregate` transitively in all the modules 🤔

[the remark this answers is not in the document]
Comment (juanpedromoreno) [reply modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt]: Fixed in https://github.com/higherkindness/mu/pull/577/commits/60d6e22c4e38cd6f70cd2ecdc45995dad216d0a9

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+  def inputFiles(files: Set[File]): Seq[File] =
+    files.filter(_.getName.endsWith(ProtoExtension)).toSeq
+
+  def generateFrom(
+      inputFile: File,
+      serializationType: String,
+      options: String*): Option[(String, Seq[String])] =
+    Option(getCode[IO](inputFile).unsafeRunSync)
+
+  val withImports: String => String = self =>
```
[the remark this answers is not in the document]
Comment (juanpedromoreno) [reply modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: Fixed in https://github.com/higherkindness/mu/pull/577/commits/60d6e22c4e38cd6f70cd2ecdc45995dad216d0a9

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 11]
```diff
@@ -0,0 +1,82 @@
...
+  val copRegExp: Regex = """((Cop\[)(((\w+)(\s)?(\:\:)(\s)?)+)(TNil)(\]))""".r
+
+  val cleanCop: String => String =
+    _.replace("Cop[", "").replace("::", ":+:").replace("TNil]", "CNil")
+
+  val withCoproducts: String => String = self =>
+    copRegExp.replaceAllIn(self, m => cleanCop(m.matched))
+
+  val parseProtocol: Protocol[Mu[ProtobufF]] => higherkindness.skeuomorph.mu.Protocol[Mu[MuF]] =
+    p => higherkindness.skeuomorph.mu.Protocol.fromProtobufProto(p)
```
Comment (fedefernandez) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]:
```suggestion
    higherkindness.skeuomorph.mu.Protocol.fromProtobufProto
```

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+
+  val printProtocol: higherkindness.skeuomorph.mu.Protocol[Mu[MuF]] => String = p =>
+    higherkindness.skeuomorph.mu.print.proto.print(p)
```
Comment (fedefernandez) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]:
```scala
  val printProtocol: higherkindness.skeuomorph.mu.Protocol[Mu[MuF]] => String =
    higherkindness.skeuomorph.mu.print.proto.print
```

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 13]
```diff
@@ -0,0 +1,82 @@
...
+  val idlType: String = proto.IdlType
+
+  def inputFiles(files: Set[File]): Seq[File] =
+    files.filter(_.getName.endsWith(ProtoExtension)).toSeq
+
+  def generateFrom(
+      inputFile: File,
+      serializationType: String,
+      options: String*): Option[(String, Seq[String])] =
+    Option(getCode[IO](inputFile).unsafeRunSync)
```
Comment (fedefernandez) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: I prefer the `unsafeRunSync` at the very edge 
```scala
getCode[IO](inputFile).map(Some(_)).unsafeRunSync
```

File: modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala [hunk 14]
```diff
@@ -0,0 +1,82 @@
...
+  def withImports(self: String): String =
+    (self.split("\n", 2).toList match {
+      case h :: t => imports(h) :: t
+      case a      => a
+    }).mkString("\n")
+
+  val copRegExp: Regex = """((Cop\[)(((\w+)(\s)?(\:\:)(\s)?)+)(TNil)(\]))""".r
+
+  val cleanCop: String => String =
+    _.replace("Cop[", "").replace("::", ":+:").replace("TNil]", "CNil")
```
Comment (pepegar) [inline modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala]: In the future we can change this in skeuomorph directly

File: modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt [hunk 15]
```diff
@@ -0,0 +1,18 @@
...
+    mappings in (Compile, packageBin) ~= { _.filter(!_._1.getName.endsWith(".class")) },
+    idlType := "proto",
+    srcGenSourceDirs := Seq((Compile / resourceDirectory).value),
+    srcGenTargetDir := (Compile / sourceManaged).value / "compiled_proto",
+    sourceGenerators in Compile += (Compile / srcGen).taskValue,
+    addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.patch),
+    libraryDependencies ++= Seq(
+        "io.higherkindness"    %% "mu-rpc-channel" % sys.props("version"),
+        "io.higherkindness"    %% "mu-rpc-fs2" % sys.props("version"),
+        "com.chuusai" %% "shapeless" % "2.3.2"
```
Comment (AdrianRaFo) [inline modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt]: 2.3.3 is available

Comment (juanpedromoreno) [reply modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/srcProtoGenFromDirs/build.sbt]: This is just an scripted test ;)
